---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbimq-01
  labels:
     disk: "rabbitmq-01"
spec:
  capacity:
    storage: 50Gi
  hostPath:
    path: /opt/minikube/app/rabbitmq
    type: DirectoryOrCreate
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbimq-02
  labels:
     disk: rabbitmq-02
spec:
  capacity:
    storage: 50Gi
  hostPath:
    path: /opt/minikube/app/rabbitmq
    type: DirectoryOrCreate
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rabbitmq